.TH KAPOW 1 "April 2021" "Kapow 1.5.10" "General Commands Manual"

.SH "NAME"
kapow \- punch clock program

.SH "SYNOPSIS"
.B kapow
[options]
.RI [ filename ]

.SH "DESCRIPTION"
Kapow is a punch clock program designed to easily keep track of your hours,
whether you're working on one project or many. Simply clock in and out with
the Start/Stop button. If you make a mistake in your hours, you can go back
and edit any of the entries by double-clicking on the session in question.
Kapow also allows you to easily keep track of the hours since you last
billed a client, by providing a helpful "Billed" checkbox\-\-the totals will
reflect your work after the last billed session.

.SH "OPTIONS"
.TP
.BR \-h ", " \-\-help
Displays help on commandline options.
.TP
.B \-\-help-all
Displays help including Qt specific options.
.TP
.BR \-v ", " \-\-version
Displays version information.
.TP
.B \-\-ini\=FILE
Store settings as INI format in specified file.
.TP
.B \-\-no\-backups
Do not create automatic backups of time data.
.TP
.I filename
Time data file to use.

.SH "SEE ALSO"
.BR qt5options (7)

.SH "REPORTING BUGS"
Report bugs to <kapow@bugs.gottcode.org>.

.SH "COPYRIGHT"
Copyright \(co 2008-2021 Graeme Gott
.PP
Free use of this software is granted under the terms of the GNU General
Public License version 3 (GPLv3). There is NO WARRANTY, to the extent
permitted by law.

.SH "AUTHOR"
Graeme Gott <graeme@gottcode.org>.
