.TH KAPOW "1" "February 2014"

.SH "NAME"
kapow \- punch clock program

.SH "SYNOPSIS"
.PP
.B kapow
[\fB\-\-ini\fR\=\fIFILE\fR]
[\fB\-\-no\-backups\fR]
[filename]

.SH "DESCRIPTION"
.PP
\fIKapow\fR is a punch clock program designed to easily keep track of your hours,
whether you're working on one project or many. Simply clock in and out with
the Start/Stop button. If you make a mistake in your hours, you can go back
and edit any of the entries by double-clicking on the session in question.
Kapow also allows you to easily keep track of the hours since you last
billed a client, by providing a helpful "Billed" checkbox\-\-the totals will
reflect your work after the last billed session.

.SH "OPTIONS"
.TP
\fB\-\-ini\fR\=\fIFILE\fR
Store settings as INI format in specified file.
.TP
\fB\-\-no\-backups\fR
Do not create automatic backups of time data.

.SH "COPYRIGHT"
.PP
Copyright \(co 2014 Graeme Gott
.PP
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.
.PP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.

.SH "AUTHOR"
.PP
Graeme Gott <graeme@gottcode.org>.
